# Generated by Django 3.1.1 on 2020-09-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BassTrombones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=50)),
                ('number_of_valves', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double')], max_length=6)),
                ('valve_configuration', models.CharField(choices=[('Not applicable', 'Not applicable'), ('Dependent', 'Dependent'), ('Independent', 'Independent')], max_length=14)),
                ('valve_type', models.CharField(max_length=50)),
                ('wrap', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=6)),
                ('bell_size', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Bell size (inches)')),
                ('bell_material', models.CharField(max_length=30)),
                ('bore', models.CharField(choices=[('Dual bore', 'Dual bore'), ('Not dual bore', 'Not dual bore')], max_length=13)),
                ('finish', models.CharField(max_length=30)),
                ('outer_slide_material', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CustomizableBassTrombones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trombone', models.CharField(max_length=100)),
            ],
        ),
    ]
