# Generated by Django 3.1.1 on 2020-09-20 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0002_auto_20200920_0123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomizableBassTrombone',
        ),
    ]
