# Generated by Django 3.1.1 on 2020-09-20 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0004_customizablebasstrombone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basstrombone',
            old_name='bore',
            new_name='dual_bore',
        ),
    ]
