# Generated by Django 3.1.1 on 2020-09-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0006_auto_20200920_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bellmaterial',
            name='id',
        ),
        migrations.RemoveField(
            model_name='bellsize',
            name='id',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='id',
        ),
        migrations.RemoveField(
            model_name='finish',
            name='id',
        ),
        migrations.RemoveField(
            model_name='outerslidematerial',
            name='id',
        ),
        migrations.RemoveField(
            model_name='valvetype',
            name='id',
        ),
        migrations.AlterField(
            model_name='bellmaterial',
            name='bell_material',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bellsize',
            name='bell_size',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Bell size (inches)'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='finish',
            name='finish',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='outerslidematerial',
            name='outer_slide_material',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='valvetype',
            name='valve_type',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
