# Generated by Django 3.1.1 on 2020-09-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0009_basstrombone_bellmaterial_bellsize_brand_finish_outerslidematerial_valvetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bellsize',
            name='bell_size',
            field=models.DecimalField(decimal_places=1, max_digits=3, primary_key=True, serialize=False, verbose_name='Bell size (inches)'),
        ),
    ]
