# Generated by Django 3.1.1 on 2020-09-20 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0010_auto_20200920_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basstrombone',
            name='bell_size',
        ),
        migrations.DeleteModel(
            name='BellSize',
        ),
    ]
