# Generated by Django 3.1.1 on 2020-09-20 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0011_auto_20200920_1153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BassTrombone',
        ),
        migrations.DeleteModel(
            name='BellMaterial',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Finish',
        ),
        migrations.DeleteModel(
            name='OuterSlideMaterial',
        ),
        migrations.DeleteModel(
            name='ValveType',
        ),
    ]
