# Generated by Django 3.1.1 on 2020-09-20 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0013_basstrombone_bellmaterial_bellsize_brand_finish_outerslidematerial_valvetype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomizableBassTrombone',
        ),
    ]
