# Generated by Django 3.1.1 on 2020-09-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0014_delete_customizablebasstrombone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizableBassTrombone',
            fields=[
                ('trombone', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
