# Generated by Django 3.1.1 on 2020-09-20 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0015_customizablebasstrombone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basstrombone',
            options={'ordering': ['brand', 'model']},
        ),
        migrations.AlterModelOptions(
            name='bellmaterial',
            options={'ordering': ['bell_material']},
        ),
        migrations.AlterModelOptions(
            name='bellsize',
            options={'ordering': ['bell_size']},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['brand']},
        ),
        migrations.AlterModelOptions(
            name='customizablebasstrombone',
            options={'ordering': ['bass_trombone']},
        ),
        migrations.AlterModelOptions(
            name='finish',
            options={'ordering': ['finish'], 'verbose_name_plural': 'finishes'},
        ),
        migrations.AlterModelOptions(
            name='outerslidematerial',
            options={'ordering': ['outer_slide_material']},
        ),
        migrations.AlterModelOptions(
            name='valvetype',
            options={'ordering': ['valve_type']},
        ),
        migrations.RenameField(
            model_name='customizablebasstrombone',
            old_name='trombone',
            new_name='bass_trombone',
        ),
    ]
