# Generated by Django 3.1.1 on 2020-09-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0016_auto_20200920_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bellsize',
            name='bell_size',
            field=models.DecimalField(decimal_places=1, max_digits=3, primary_key=True, serialize=False, verbose_name='bell size (inches)'),
        ),
    ]
